baseurl = "http://cmcr-class.rbind.io"
relativeurls = false
languageCode = "en-us"
title = "POLI 7002/7450"
theme = "hugo-fs-theme"
googleAnalytics = ""
disqusShortname = "cmcr-class"
ignoreFiles = ["\\.Rmd$", "_files$", "_cache$"]
uglyURLS = false
enableEmoji = true
blogdir = "blog"

[permalinks]
    post = "blog/:year/:month/:day/:slug/"

[[menu.main]]
    name = "Home"
    url = "/"
    weight = 1
[[menu.main]]
    name = "Syllabus"
    url = "https://github.com/cmcr-class/cmcr-class.rbind.io/blob/master/syllabus/7450CMCR_Syl.pdf"
    weight = 2
[[menu.main]]
    name = "Slides"
    url = "https://github.com/cmcr-class/cmcr-class.rbind.io/tree/master/slides"
    weight = 3
[[menu.main]]
    name = "Blog"
    url = "/blog/"
    weight = 4
[[menu.main]]
    name = "Discussion"
    url = "https://github.com/orgs/cmcr-class/teams/students/discussions/"
    weight = 5

[params]
    description = "Computational Methods for Comparative Research"
    subtitle = "Prof. Frederick Solt"
    home_text = "In this course, you will learn to identify common methodological issues encountered in quantitative comparative research and to address them using computational techniques.  Topics covered include data wrangling, exploration, and analysis (i.e., 'data science'); Bayesian estimation of latent variables such as democracy, judicial independence, and respect for human rights across countries and over time; and computational approaches to the study to the dynamics of public opinion both within and across countries. This course is cross-listed in Comparative Politics and Methodology; it may be used to meet requirements in either subfield (but not both)."

    author = "Frederick Solt"
    dateFormat = "2006/01/02"
    email = "frederick-solt@uiowa.edu"
    github_username = "cmcr-class"

    # options for highlight.js (version, additional languages, and theme)
    highlightjsVersion = "9.12.0"
    highlightjsCDN = "//cdnjs.cloudflare.com/ajax/libs"
    highlightjsLang = ["r", "yaml"]
    highlightjsTheme = "github"

    MathJaxCDN = "//cdnjs.cloudflare.com/ajax/libs"
    MathJaxVersion = "2.7.5"

    [params.logo]
    url = "cmcr.png"
    width = 50
    height = 50
    alt = "CMCR"

